### ISSUE TITLE
Accessing Course "C for Programmers" not working for German Udacity Page

### ISSUE THREAD

**Issue by silentwater** [udacity/isdc_issues_tracker#1]
I tried accessing the course "C for Programmers".

I'm usualy using the Udacity Website in German (using Chrome), so when I clicked the Link https://www.udacity.com/course/c-for-programmers--ud210 I was redirected to https://de.udacity.com/course/c-for-programmers--ud210 which showed me the  Udacity 404 Page (Page can't be found).

I tried to open the course in a different browser (Firefox) and was asked to choose the language. This time I was choosing English and the Link worked. Trying the redirected link address for the German language showed me again the 404 page.

**Comment by subamrana** [comment]
Same for Indian site. Page can't be found. Informed udacity support team.

**Comment by andrewpaster** [comment]
Hey sorry for taking so long to get back to you on this. I let the team know about the redirect issue. It looks like the Indian site is working now but not the German one.
