### ISSUE TITLE
Typo in L4.7 Question 2 of 5

### ISSUE THREAD

**Issue by carsten-grimm** [udacity/isdc_issues_tracker#10]
The question reads "QUESTION 2 OF 5

If A and B are NOT independent events, and P(A) = 0.2 and P(B) = 0.1, what is P(A|B)?"

Considering the question right before, I assume you meant "P(A, B)" instead of "P(A | B)"?

**Comment by AndyAtUdacity** [comment]
Thank you for noticing this! Definitely meant it the way you said :) Fixed now!
