### ISSUE TITLE
C++ Getting started, Function Signatures1

### ISSUE THREAD

**Issue by JonathanKSullivan** [udacity/isdc_issues_tracker#104]
Explain this line: <vector<float>> unnormalized, normalized, result; as it’s the first time we see a definition of several variables in the same line. Also, for clarity, provide the code related to the functions “show_grid”, “normalize”, “close_enough”, so we have a reference of what those actually do

**Comment by AndyAtUdacity** [comment]
It looks like a comment was already added explaining that line of code.
