### ISSUE TITLE
Car simulator

### ISSUE THREAD

**Issue by m0hamed-alaa** [udacity/isdc_issues_tracker#11]
can't access the car simulator

**Comment by m0hamed-alaa** [comment]
when I click on the launch car simulator button , another window opens and the simulator begins to load but it never runs !
It shows me messages like "RunTime not initialized yet" or " Failed to load resource :net :: ERR_SPDY_PROTOCOL_ERROR".

**Comment by AndyAtUdacity** [comment]
This should be fixed now. Could you try again and let me know if it's working for you?

**Comment by m0hamed-alaa** [comment]
It's working well now .. thanks
