### ISSUE TITLE
C++ Object Oriented Programming, Anatomy of a Class

### ISSUE THREAD

**Issue by JonathanKSullivan** [udacity/isdc_issues_tracker#116]
Easy to follow - for me though, I think it would be a bit more interpretable if you have a summary at the end. It is hard to read about each section, then see the code, then see information on the next part of the class, then see following code.

**Comment by andrewpaster** [comment]
I put an extra text node at the bottom showing the full class again, and added some extra comments to make it clear which sections mapped to which parts of the lesson page.
