### ISSUE TITLE
C++ Object Oriented Programming, Class File Structure

### ISSUE THREAD

**Issue by JonathanKSullivan** [udacity/isdc_issues_tracker#118]
Perfect - this is good. I was imagining the previous lesson to look similar to this. Tips like this: "Generally, it's recommended to put the minimum number of #include statements needed into a header file." are extremely valuable. As I mentioned earlier, it would be great if these were summarized somewhere on a cheat sheet.

**Comment by andrewpaster** [comment]
Thanks for posting this feedback. Sounds like this student wants a C++ e-book, which is a cool idea although probably don't have the manpower for it at the moment.
