### ISSUE TITLE
Review needs your attention : But review was released by reviewer

### ISSUE THREAD

**Issue by Chennu** [udacity/isdc_issues_tracker#12]
"Review needs your attention" notification is showing in MyClassRoom. But review was under pending and there are no comments from reviewer.

**Comment by Chennu** [comment]
![ReviewNeedsAttentionNotification.png](https://waffleio-direct-uploads-production.s3.amazonaws.com/uploads/59ded8fd74352200128cc996/125516c66e82c728ace21e0d46da918c2a8794878aecbb508549e49127522e7c272aac3f7983ea2bbe56720e014d52be011a001ea9aacd39aca43979d8550ee9d53f5f77cf6915abb8821eed07ec748f4bd3a4a0980e91b6697abad2c51a7c0c0f0a88f75734a5994ccf5ff14ae54454a115242e.png)
![ProcessingProjectSubmission.png](https://waffleio-direct-uploads-production.s3.amazonaws.com/uploads/59ded8fd74352200128cc996/125516c66e82c728ace21e0d46d88695208790ba86e7b873b652fa912a5214662b09aa38638cec26fd0e39111d0014f9121c4d4eeefc8079afb33874d85c08e485695874c63c43aaeed61bbb57a83c990dd4e8e8d51199a26867f5819d4e3614041d89f85a32a7984dcf5bff42f300.png)

**Comment by Chennu** [comment]
![Screen Shot 2017-10-11 at 11.02.41 PM.png](https://waffleio-direct-uploads-production.s3.amazonaws.com/uploads/59ded8fd74352200128cc996/125516c66e82c728ace21e0d46db978826878de9bce1b057e40fa0c57e0b76236455f26b7191a379ee0c2b53415b4fbc21254d58eeb9cb74fce36f34985619e8d83f5671c23943acbb8b4bbb06ba208a1d83e0e88e4896fa2137a5dad11b61435c52dcbd4f3fb2984cc259f34be64a52a310316be774376e0a.png)

**Comment by andrewpaster** [comment]
Hi, Sorry it's taken so long to get back to you. It sometimes takes a few weeks to respond via waffleboard. For immediate issues like this one that block your progress, try contacting  introsdc-support@udacity.com  I assume this has already been resolved but let us know. Again apologies for getting back to you so late.
