### ISSUE TITLE
Translate Python to C++ and 2D Hist in Python

### ISSUE THREAD

**Issue by JonathanKSullivan** [udacity/isdc_issues_tracker#122]
We need a QnA for 2D hist in python similar to the SDC program, I handle the live help and see students asking questions like where/how to start working on this 2d hist project

**Comment by andrewpaster** [comment]
Do you mean the 2D Histogram Python project or the 2D Python to C++ translation project? Or both?

**Comment by JonathanKSullivan** [comment]
I believe first, I received this info from chartio

**Comment by AndyAtUdacity** [comment]
This would require a fair amount of new content. I'm going to assign to you @dsilver829 :D

**Comment by mvirgo** [comment]
Just added some good tips for the Translate Python to C++ one; will circle back on the 2D Histogram in Python to check this out more

**Comment by mvirgo** [comment]
Looks fine on this one for now, don't see a lot of questions or feedback on it anymore.
