### ISSUE TITLE
Need additional test(s)

### ISSUE THREAD

**Issue by JonathanKSullivan** [udacity/isdc_issues_tracker#124]
The following equation passes both tests but is an incorrect answer.

probability = (high_range - low_range) / maximum - minimum

https://classroom.udacity.com/nanodegrees/nd113/parts/70e3b7ce-c552-4867-984e-ebbfb6c786ec/modules/bb316d89-3a59-4093-b62d-f36d7822e530/lessons/31a8e9fd-58d6-4398-bc07-a3ba0dd9fe5f/concepts/82c79821-dced-4f29-9b33-f09798aadacc

**Comment by andrewpaster** [comment]
good point - I added an extra test case
