### ISSUE TITLE
Part(6) Data structures

### ISSUE THREAD

**Issue by m0hamed-alaa** [udacity/isdc_issues_tracker#125]
I can't connect to my workspace in part(6) lesson (2) Data structures . It shows loading and nothing happens after that . just a blank page.
Is this happening to anyone else or it's just me ?

**Comment by m0hamed-alaa** [comment]
![Screenshot 2017-12-01 13.44.17.png](https://waffleio-direct-uploads-production.s3.amazonaws.com/uploads/59de9ce0908ea90013482030/125516c66e82c728ace21e0d46db978826878dba87e6ab03f60da1c36417753e7955e37a23cbb77cf1132c43434d0eee1e020a17b8eb8339a3bf6e798f580fbfd16e5620c23a11acb9d019e955be24dd5d99a4fedb1294b7607caddecd5d340c041083fe5834a2984fcd51f348e94951b65e.png)
![Screenshot 2017-12-01 13.45.20.png](https://waffleio-direct-uploads-production.s3.amazonaws.com/uploads/59de9ce0908ea90013482030/125516c66e82c728ace21e0d46db978826878dba87e6ab03f60da1c36417753e7955e37a23cbb77df1102b43434d0eee1e020a17b8eb8339a3bf6e798f580fbfd16e5620c23a11acb9d019e955be24dd5d99a4fedb1294b7607caddecd5d340c071983fe5834a2984fcd51f04ee64c5db65e.png)

**Comment by andrewpaster** [comment]
Hey, sorry for the late response. It might be that the workspace was loaded and then somebody at Udacity changed the files. Or it might just be that something is down currently and things will work if you wait a few minutes. 

Also, if you go to the "Menu" at the bottom left corner of the screen, click on "Refresh Workspace". This will not erase your work.

If that doesn't work, you can also try "Reset Data", but that will erase all of your work from the current lesson. You can always download the files you've already worked on first before hitting Reset Data.
