### ISSUE TITLE
Submit answer not working for 2.12

### ISSUE THREAD

**Issue by ortizjuan2** [udacity/isdc_issues_tracker#126]
Following text always appears when submitting answer:
{u'vm_time': 0.12155985832214355, u'stdout': u'', u'vm_creation_time': 7.6055526733398438e-05, u'test_results': [], u'stderr': u'Traceback (most recent call last):\n File "vm_main3.py", line 47, in \n import main\n File "/tmp/vmuser_qmtdqpjpve/main.py", line 2, in \n import aiMain\n File "/tmp/vmuser_qmtdqpjpve/aiMain.py", line 22\n \uff03\u4e0b\u9762\u7684\u4ee3\u7801\u7c7b\u4f3c\u4e8e\u4f18\u8fbe\u5b66\u57ce\n ^\nSyntaxError: invalid character in identifier\n', u'exec_server_time': 0.12511277198791504, u'exec_status': u'error'}
Thank you for your submission!

**Comment by bartmate** [comment]
The same here.

**Comment by krasing** [comment]
![Screenshot from 2017-12-01 13-16-26.png](https://waffleio-direct-uploads-production.s3.amazonaws.com/uploads/5a213afedbd88500134ecd11/125516c66e82c728ace21e0d46db978826878dba87e6ab03a24fff99691477227e49f2793dd5b268ee11365059424caa53444d04bea6d37ef5f22e7a985902bfd8685b70943d12a5ec8618bf01bb728d19d1b2b8dc5edcfa7f74b9dfd0126754505a9bf54f37a1934acd59f44ae34a56a3113766e6647b.png)

**Comment by YCSU** [comment]
Same here

**Comment by AndyAtUdacity** [comment]
Fixed this!
