### ISSUE TITLE
2/4/7 “I do not know” is a wrong answer.

### ISSUE THREAD

**Issue by bartmate** [udacity/isdc_issues_tracker#128]
I would expect a different message for answer “I do not know” than “Try again”. Something like this would be more positive:

No problem that is why you are here and you will be able to answer such questions easily after completing this lesson.

**Comment by andrewpaster** [comment]
Hi, that's a valid point. The "Try Again" is the default response. I've added some more encouraging words when somebody chooses the "I don't know" option. Although it'll still say "Try Again" at the top.
