### ISSUE TITLE
L5/15-16 Correct solution is not recognized

### ISSUE THREAD

**Issue by itsjan** [udacity/isdc_issues_tracker#13]
Probability of Collision; Submit answer, does not recognize the correct solution - even in #16 which is the suggested solution, or in #15 even if the suggested solution is copy-pasted into the editor.

**Comment by silentwater** [comment]
Can confirm this issue. Have the same Problem in L5/15-16 (Programming  Probability in Python)

**Comment by AndyAtUdacity** [comment]
Fixed! Thanks for pointing this out.
