### ISSUE TITLE
"Solving problems" lesson : 5

### ISSUE THREAD

**Issue by JonathanKSullivan** [udacity/isdc_issues_tracker#130]
Attempting the Problem the test function is wrong. The correct test should be
# test full year difference 
assert(days_between_dates(2012, 6, 29, 
2013, 6, 29) == 365) 
instead of 
# test full year difference 
assert(days_between_dates(2012, 6, 29, 
2013, 7, 29) == 365) 
i.e. use same month.

**Comment by AndyAtUdacity** [comment]
fixed
