### ISSUE TITLE
Challenge: Shortest Path - submission error

### ISSUE THREAD

**Issue by xperroni** [udacity/isdc_issues_tracker#136]
When clicking on the "Submit Answer" button for the coding challenge in Lesson 2 part 12, the following error message is displayed:

{u'vm_time': 0.17159605026245117, u'stdout': u'', u'vm_creation_time': 6.9141387939453125e-05, u'test_results': [], u'stderr': u'Traceback (most recent call last):\n File "vm_main3.py", line 47, in \n import main\n File "/tmp/vmuser_cxxwwxnfvh/main.py", line 2, in \n import aiMain\n File "/tmp/vmuser_cxxwwxnfvh/aiMain.py", line 22\n \uff03\u4e0b\u9762\u7684\u4ee3\u7801\u7c7b\u4f3c\u4e8e\u4f18\u8fbe\u5b66\u57ce\n ^\nSyntaxError: invalid character in identifier\n', u'exec_server_time': 0.1758570671081543, u'exec_status': u'error'}
Thank you for your submission!

The same message is displayed regardless any changes were made to the original code.

**Comment by andrewsdc** [comment]
Hey thanks for filing this. A couple of other students have also posted about this in issue #126. We haven't had the chance to fix the issue, but I'm going to close this one since it's already in #126.
