### ISSUE TITLE
Vanishing term from Kalman Filter formulas

### ISSUE THREAD

**Issue by bartmate** [udacity/isdc_issues_tracker#137]
Hi,
in 3. Working with Matrices / 4. Matrices and Transformation and State / 11. Simplifying the Kalman Filter Equations 
the first equation contains a term: Bu. (After simplifying it is still there in the video!)

However this term is missing from the later lessons, e.g. 14. Kalman Equation Reference.

I think this vanishing term is very confusing for those who does not understand the equations in depth (which is stated not to be a problem).

I think it should be removed during the simplification with some explanation in lesson 11, or it should be kept in lesson 14 and later explaining why it is 0.

BartMate
Beta-Tester

**Comment by andrewsdc** [comment]
Hey thanks for the feedback. I added a paragraph in Lesson 11 about Fx versus Bu
