### ISSUE TITLE
Out of memory error running simulator

### ISSUE THREAD

**Issue by xperroni** [udacity/isdc_issues_tracker#138]
When trying to run the simulator in "Part 1 - Drag Race" of the Joy Ride project, it fails with the following error:

Out of memory. If you are the developer of this content, try allocating more memory to your WebGL build in the WebGL player settings.

My machine's got 8GB RAM and a GeForce GTX 960M GPU with 2GB RAM. Neither memory is ever completely taken up.

**Comment by xperroni** [comment]
I'm running Chromium (Google Chrome's open source branch) 62.0.3202.94 on Ubuntu 17.04.

**Comment by AndyAtUdacity** [comment]
Not sure what the cause of this is but since this is the only report of a bug I'm going to mark as closed.
