### ISSUE TITLE
Missing python code in project Translate Python to C++

### ISSUE THREAD

**Issue by bartmate** [udacity/isdc_issues_tracker#139]
Hi, 

is it intentional that in localizer.py the funtion "sense" is not implemented? This is one of the code which should be translated to C++ in this project.

(Or maybe it is implemented only if the student implemented it earlier?)

Would not it be better if there would be a guaranteedly good implementation (which is independent the implementation of the student, which can be wrong or ugly)?

**Comment by AndyAtUdacity** [comment]
The sense function is implemented in the provided solution code. I suspect that you have followed the link back to YOUR python code from the histogram filter project. If you didn't complete the sense function there then this would show up as unimplemented.
