### ISSUE TITLE
No direct video download links

### ISSUE THREAD

**Issue by AnkS4** [udacity/isdc_issues_tracker#14]
In Part '3 Working with Matrices' & '4 C++ Basics', except in 'Working with Matrices>4 Matrices and Transformation of State'

**Comment by andrewpaster** [comment]
Hey, sorry for taking so long to get back to you about this. Can you provide more context? Do you mean that you can't click on the YouTube logo to open the video in youtube?

**Comment by JonathanKSullivan** [comment]
no response
