### ISSUE TITLE
Incorrect raise call in base code for project Implement a Matrix Class

### ISSUE THREAD

**Issue by xperroni** [udacity/isdc_issues_tracker#141]
The base code for project "Implement a Matrix Class" contains several raise calls of the form:

raise(ExceptionClass, 'message string')

What this does is to raise a 2-tuple containing the exception class as first element, and the message string as second. This sort of works in Python 2, but in Python 3 it produces an error of the form:

TypeError: exceptions must derive from BaseException

Which completely obscures the original error.

The correct syntax for raising an exception enclosing a custom message is:

raise ExceptionClass('message string')

**Comment by JonathanKSullivan** [comment]
The bug has been resolved.
