### ISSUE TITLE
The Search Problem: Example Route Finding

### ISSUE THREAD

**Issue by JonathanKSullivan** [udacity/isdc_issues_tracker#143]
When the paths of length 2 and 3 are marked, they appear to be only the newly marked path segment between two cities. It is not readily clear that the paths of length 2 and 3 are longer paths than this. Perhaps if the paths were highlighted in their entirety it would be clearer what they are.

**Comment by AndyAtUdacity** [comment]
This is a video issue that probably isn't worth fixing.
