### ISSUE TITLE
1-D Car World [exercise]

### ISSUE THREAD

**Issue by krasing** [udacity/isdc_issues_tracker#146]
Exercise 2 - Grid Probability
Is the grid number starting from 1  or from 0?

"The reason you would call grid_probability(my_grid, 4) is because of how lists work in python. The first element in a list is accessed with [0] rather than [1]."

print(grid_probability([.1, .1, .2, .1, .5], 2))
# will return 0.2

**Comment by andrewsdc** [comment]
Hi thanks for pointing this out. We revised some of these exercises a couple of weeks ago, and it looks like the ambiguity with the explanation and tests were changed.
