### ISSUE TITLE
2-D Self Driving Car World Solution

### ISSUE THREAD

**Issue by krasing** [udacity/isdc_issues_tracker#148]
The output of `car.visualize_probability()` could be included. I managed to get wrong distribution with all test cases passing and only the image helped me discover the error.

My error was in def initialize_grid(self):

    single_row = [probability] * self.grid_size[1]
    self.grid = [single_row] * self.grid_size[0]

**Comment by andrewsdc** [comment]
Hey this is a good point. Though we decided to remove the object oriented programming part of these exercises since object oriented programming is taught later in the nanodegree more thoroughly.
