### ISSUE TITLE
Server error while submitting the quiz

### ISSUE THREAD

**Issue by vishalrangras** [udacity/isdc_issues_tracker#151]
https://classroom.udacity.com/nanodegrees/nd113/parts/ad7e52df-3387-4252-b4bd-9c40aecb8093/modules/14fc0233-3169-4ca5-8255-ed921d2d973a/lessons/56980e75-08e4-4b3c-ba7f-58f10e963980/concepts/6146c6bc-68c8-498b-b6bd-8c16bee2886b

**Comment by vishalrangras** [comment]
While clicking on Test Run, the submission works file but when clicking on Submit Answer, I get server error.
![Capture.JPG](https://waffleio-direct-uploads-production.s3.amazonaws.com/uploads/5880fdad2a33c22000e5e186/125516c66e82c728ace21e0d46cb958a379791accda5fd53b652fa912a5265296b51fa2929d0b77cbd1228580b5b49ac41590d42aaad8d2ff0a42062c80d55b98e30063e937f03a6aa801fb500bf21894983b0b88f4cc8ed3537aa.JPG)

**Comment by andrewsdc** [comment]
Thank you for pointing this out. A couple of other students have put issues on the waffleboard about this in #126. We haven't had the chance to fix it yet. But I'm going to close this task and leave #126 open.
