### ISSUE TITLE
Inconsistent statement in Lesson 7.9 "2D Arrays and the Robot World [demonstration]"

### ISSUE THREAD

**Issue by xperroni** [udacity/isdc_issues_tracker#155]
In the second code block of Lesson 7.9 "2D Arrays and the Robot World [demonstration]" the following code is included:

    print('It\'s height is: ' + str(world.shape[1]) + 
          ', and it\'s length/width is: ' + 
    str(world.shape[0]))

This is inconsistent to how matrix dimensions were presented in the leading text; clearly `shape[0]` is the height of the matrix, and `shape[1]` is the width. Trying to introduce "length" as an equivalent term here only adds to the confusion, not least because it would more naturally be an alias to height (the first dimension) than width.

**Comment by cezannec** [comment]
Thanks for noticing this, you're right that these dimensions are opposite what they should be! shape[0] is the width (the number of columns) and shape[1] is the height (the number of rows) in the array. The code has been updated and, for clarity, I no longer use the term "length." Thanks for your feedback :)
