### ISSUE TITLE
9.18 2-D Car World [Excersize]: reference in comments to variable self.map

### ISSUE THREAD

**Issue by ddrm86** [udacity/isdc_issues_tracker#156]
In the TODO comments, there are two references to the "self.map" variable, but both times it is actually referring to the "self.grid" variable.

**Comment by andrewsdc** [comment]
Thank you for finding this and pointing it out. We ended up changing this exercises a couple of weeks ago. We took out the object oriented part since there are lessons later in the nanodegree that teach object oriented programming in more depth. Let us know if you find any other bugs.
