### ISSUE TITLE
Lessons open at revisited "Learning Objectives"

### ISSUE THREAD

**Issue by xperroni** [udacity/isdc_issues_tracker#157]
If a Lesson revisits a "Learning Objectives" part from a previous Lesson, it opens at that part rather than the beginning.

For example, Lesson 6.6 "Learning Objectives -
 Bayes' Rule" is revisited in part 4 of Lesson 8 "Probability Distributions". When opening Lesson 8 for the first time, the lesson opens at part 4 instead of part 1 as would be expected.

It may be that this behavior occurs only if the student (successfully) completes any questions in "Learning Objectives", which was my case.

**Comment by andrewpaster** [comment]
Weird. I'll let the team that develops the classroom backend know about the behavior.
