### ISSUE TITLE
Contents in Part 5 onwards are locked

### ISSUE THREAD

**Issue by AnkS4** [udacity/isdc_issues_tracker#16]
![2017-10-12-140932_1366x768_scrot](https://user-images.githubusercontent.com/14903065/31487058-0ffc847a-af57-11e7-8d7d-1c12b51a60db.png)

**Comment by subamrana** [comment]
That's so because they are still working on those lessons. That is not a bug.

**Comment by AndyAtUdacity** [comment]
confirmed, this is intentional and this content will be released incrementally.
