### ISSUE TITLE
Quiz not working Lesson 4.19, 4.20, 4.21 and 4.22

### ISSUE THREAD

**Issue by ortizjuan2** [udacity/isdc_issues_tracker#160]
The quizzes for lessons 4.19, 4.20, 4.21 and 4.22 are not working, neither the "start quiz" nor the Next button will trigger the quiz.

**Comment by andrewpaster** [comment]
Hey, sorry it's taken a couple of weeks to get back to you about this. Is this the Conditional Probability Lesson? The quizzes in that section are working for me. What browser/OS are you using?

**Comment by JonathanKSullivan** [comment]
No response
