### ISSUE TITLE
Jupyter Python Errors in Route Planner Project

### ISSUE THREAD

**Issue by zeeexsixare** [udacity/isdc_issues_tracker#162]
Python errors arise when attempting to import pickle files.  See screenshot.  Multiple users affected.

**Comment by zeeexsixare** [comment]
![image](https://user-images.githubusercontent.com/32753720/34139954-97550492-e445-11e7-8348-c9ee1af7a29b.png)

**Comment by joebenderweb** [comment]
I noticed this problem also. load_map is not working, and I can't continue work on the project.

**Comment by AndyAtUdacity** [comment]
Fixed on December 19th. Problem was caused by serialization of the map using an old version of networkx
