### ISSUE TITLE
Section 4 lesson 2 "C++ Vectors TODO #2

### ISSUE THREAD

**Issue by JonathanKSullivan** [udacity/isdc_issues_tracker#163]
TODO #2"fill the float vector with the following values: 4.5, 2.1, 8.54, 9.0," the solution shows " vector1[0] = 4.5; vector1[0] = 2.1; vector1[0] = 8.54; vector1[0] = 9.0;" This would just overwrite vector1[0] each time, and should be vector1[0] = 4.5; vector1[1] =2.1; vector1[2] = 8.54; vector1[3] = 9.0;

**Comment by andrewpaster** [comment]
Fixed!
