### ISSUE TITLE
Inconsistency between video & quiz

### ISSUE THREAD

**Issue by bartmate** [udacity/isdc_issues_tracker#165]
In Lesson 2 (Accelerometers, ...), 5 Reasoning about two peaks:
In the video it is said that first region belong to that time when “the elevator just started moving upwards”, however in the quiz it is said that in region one there is no move (and this is the correct one).

**Comment by AndyAtUdacity** [comment]
Not actually a mistake. The audio is "the first section is from when I started collecting data until the elevator starts moving upwards." The word "until" makes this correct.
