### ISSUE TITLE
Quiz cannot be used on iPad in Chrome

### ISSUE THREAD

**Issue by bartmate** [udacity/isdc_issues_tracker#167]
7. Vehicle Motion and Control,
Lesson 1 (odometers...)
6. reducing dt 

On iPad with chrome, I cannot drag the colorful elements, instead the page is scrolled. So this quiz cannot be solved.

**Comment by mvirgo** [comment]
Finally got a chance to check this. May have been fixed in the meantime, but it looks like if you hold down for an extra split second over a given element, it will have a slight visual effect and then allow you to drag it over.
