### ISSUE TITLE
Typo L1 C++ Optimization

### ISSUE THREAD

**Issue by alexandervlahakis** [udacity/isdc_issues_tracker#168]
Section 7 on Binary. 

"How Bytes Limit Value Ranges
In C++, your variables will take up either 8, 16, 32, or 64 bits of memory, which are 1, 2, 3, and 4 bytes respectively."

8, 16, 32 or 64 bits of memory, which are 1, 2, 4*, 8* bytes respectively.

**Comment by andrewpaster** [comment]
Thanks for letting us know! It's been updated in the classroom.
