### ISSUE TITLE
Bayes: Histogram Filter should be wrapped in the project design scheme

### ISSUE THREAD

**Issue by alexandervlahakis** [udacity/isdc_issues_tracker#17]
Project 1: 2D Histogram Filter in Python is listed in the syllabus but the course section itself is not listed as a 'project'.  Not sure if this is by design or not.  

- The section does not have the blue 'project' design layout.  
- Also, *I think* because it is not listed as a project the progress of the course is thrown a little bit off.  It is showing that I am done with the section on Bayesian Thinking (green checkmark next to the section) after just completing Project 0.

**Comment by AndyAtUdacity** [comment]
This is because technically it's not a "project" since it isn't submitted for manual review.
