### ISSUE TITLE
Traffic Sign Classifier test always passes

### ISSUE THREAD

**Issue by davinderc** [udacity/isdc_issues_tracker#170]
The `test_red_as_green` method in the test_functions.py file for the Traffic Sign Classifier is incorrect. In line 57, it does not check the predicted label against a green label reference. It instead checks the true label against a yellow label reference, which will never happen and the test will always pass.

**Comment by davinderc** [comment]
I believe that line should be `self.assertNotEqual(predicted_label, [0, 0, 1])`

**Comment by cezannec** [comment]
Thank you so much for catching this!! You're correct. This test code was from an older version of the project that used differently labeled images, and this has now been updated.

**Comment by cezannec** [comment]
As a note, this change has been pushed for new students who are just approaching the project; for you to see this change, you'll have to click Menu > Reset data. A reset will clear all of the project code and update it (you would lose your work in your current notebook). So, in your case, I'd suggest manually updating the test.
