### ISSUE TITLE
Lesson 9 Visualizations

### ISSUE THREAD

**Issue by ortizjuan2** [udacity/isdc_issues_tracker#171]

**Comment by ortizjuan2** [comment]
Visualizations when plotting in Jupyter notebook does not shown, please include the directive %matplotlib inline after importing matplotlib

**Comment by andrewpaster** [comment]
Hi, thanks for catching this. It's been updated in the classroom although you won't see the updates unless you reset the workspace (which I don't recommend because you'll lose your work).
