### ISSUE TITLE
A* project road description

### ISSUE THREAD

**Issue by orenmeiri** [udacity/isdc_issues_tracker#173]
In the project notebook I find this description not very clear.
The `roads` property is a list where `roads[i]` contains a list of the intersections that intersection `i` connects to.

I think this a better explanation
The `roads` property is a list where if i is an intersection, `roads[i]` contains a list of the intersections that intersection `i` connects to.

**Comment by AndyAtUdacity** [comment]
I like your version more too :) Just made that change!
