### ISSUE TITLE
Typo

### ISSUE THREAD

**Issue by taostlt** [udacity/isdc_issues_tracker#178]
https://classroom.udacity.com/nanodegrees/nd113/parts/70e3b7ce-c552-4867-984e-ebbfb6c786ec/modules/bb316d89-3a59-4093-b62d-f36d7822e530/lessons/31a8e9fd-58d6-4398-bc07-a3ba0dd9fe5f/concepts/2e63309f-e9aa-485c-a87e-e6fc6121f483

Typo:
"Notice how the code first create a new row and then appends the row to the 2D list."

'create' => 'creates'

**Comment by andrewsdc** [comment]
Thank you! It's fixed. But you won't see the change unless you Reset the workspace.
