### ISSUE TITLE
"Something went wrong!" error message at the end of graduation process

### ISSUE THREAD

**Issue by xperroni** [udacity/isdc_issues_tracker#179]
After performing identification, answering the reflection questionnaire and clicking the "graduate" button, an error message was displayed: "something went wrong! Contact (support email address)". However after reloading the graduation process page, a successful graduation page was displayed, allowing the certificate to be downloaded.

I am running Chromium (the open-source upstream project for Google Chrome) 63.0.3239.84 on Kubuntu Linux 17.04.

**Comment by andrewsdc** [comment]
Thanks for letting us know about this. We'll let engineering know about the behavior.

**Comment by JonathanKSullivan** [comment]
I think this is a one-off error... closing

**Comment by dsilver829** [comment]
I worry it's not one-off, but unless we can reproduce it's going to be hard to fix. Let's keep an eye out for any other students that report this, so we can see if it's part of a larger trend.
