### ISSUE TITLE
Live Help not working properly

### ISSUE THREAD

**Issue by mjaything** [udacity/isdc_issues_tracker#18]
I'm using a Chrome. I could type in words, but sometimes I just can't click 'end chat', or rate stars. I have to refresh the page every time. It's very annoying. Anybody suffering from this issue? or is it just me?

**Comment by andrewsdc** [comment]
Hey sorry for the delay in getting back to you about this. Are you still having this issue?

**Comment by andrewsdc** [comment]
Hi, sounds like live help was removed from the program at the end of November. So I'll close this issue. Thanks for letting us know about the issue.
