### ISSUE TITLE
42. Convolution in Self-Driving Cars

### ISSUE THREAD

**Issue by krasing** [udacity/isdc_issues_tracker#180]
In the text under the video - the statement "For sound, frequency actually refers to how fast a sound wave is moving to make a certain pitch" is not quite true - the speed of sound is constant, about 340 m/s. May be something like how fast the pressure is changing will be more correct.

**Comment by cezannec** [comment]
Thank you for this note! The speed of the wave was referring to the cycles per second; this has been clarified and an image of high and low frequency sound waves has been added :)
