### ISSUE TITLE
CV2 Won't Load

### ISSUE THREAD

**Issue by zeeexsixare** [udacity/isdc_issues_tracker#181]
See screenshot.  Seems to be persistent on many users across several (all?) notebooks using cv2.

**Comment by zeeexsixare** [comment]
![image](https://user-images.githubusercontent.com/32753720/34720130-a2fc568e-f50b-11e7-8a75-5204e1eac121.png)

**Comment by silentwater** [comment]
Can confirm  this issue. Was working beforhand but now not anymore. Also reseting the workbook or restarting the Kernel doesn't fix the problem.

If I switch the Kernel to Python 2 instead of Python 3 it is working.

**Comment by andrewsdc** [comment]
Hey, we're talking to the engineering team to figure out the issue, and we're working on a fix. Thanks for letting us know.

**Comment by JonathanKSullivan** [comment]
This has been resolved. Workspaces rolled back changes
