### ISSUE TITLE
Urgent! Restore all images from Traffic Light Classifier

### ISSUE THREAD

**Issue by neocsr** [udacity/isdc_issues_tracker#184]
One of my mentees has overwritten all the images and changed the H values for all of them. I think this is affecting everyone.

**Comment by neocsr** [comment]
![image_overwritten.png](https://waffleio-direct-uploads-production.s3.amazonaws.com/uploads/5a55bc9a99ad8400129055ed/125516c66e82c728ace21e0d46e1999b2487bca699ecad54b654e4802c48653f6b14b1247a80e03cfd183954560d47a9455c0d44fff0dd2fa1b63c71d85a5db9d5690966da2f53fde6d640e258f075c95d8fa4bd8246c1ed3c20e0888c4a3c1e05108bed10.png)

**Comment by JonathanKSullivan** [comment]
Have him download his notebook and  "reset data" from the menu at the bottom left hand side of the notebook.
