### ISSUE TITLE
Lesson 1.4 C++ Intro to Optimization - Embedded Terminal Explanation

### ISSUE THREAD

**Issue by ddrm86** [udacity/isdc_issues_tracker#185]
In the video explaining the embedded terminal the edges of the terminal window are outside off the screen, making following the explanations hard sometimes, since part of the menus are cut and the mouse pointer disappears sometimes.

**Comment by JonathanKSullivan** [comment]
Hello, 
Do you mind giving me the module name, lesson name and node name?

**Comment by ddrm86** [comment]
In Module 5. Performance Programming in C++, Lesson 1. Intro to Optimization, Node 4 Embedded Terminal Explanation.
There is a video after the first picture.

**Comment by JonathanKSullivan** [comment]
Not able to fix
