### ISSUE TITLE
Bayesian Thinking Lesson 5 part 12: matplotlib plot not inline

### ISSUE THREAD

**Issue by MxAxG** [udacity/isdc_issues_tracker#186]
Basic data visualisation optional section code doesn't produce histogram plot inline.

This should be resolved either through iPython notebook config or by adding line %matplotlib inline to the first line of the code cell.

**Comment by MxAxG** [comment]
Basic data visualisation optional section code doesn't produce histogram plot inline.

This should be resolved either through iPython notebook config or by adding line `%matplotlib inline` to the first line of the code cell.

**Comment by MxAxG** [comment]
Same issue in Bayesian Thinking Lesson 8 part  7, penultimate code cell. Leads me to believe theres an issue with iPython notebook config rather than `%matplotlib inline` being omitted both times.

**Comment by AndyAtUdacity** [comment]
fixed
