### ISSUE TITLE
Bayesian Thinking Lesson 7 part 9: numpy shape

### ISSUE THREAD

**Issue by MxAxG** [udacity/isdc_issues_tracker#187]
3rd print function in 2nd code cell incorrectly equates height to 5 and width to 6.

Given that `(6, 5) = np.shape(world)`, x (a.k.a. width) = 5 and y (a.k.a. height) = 6.

**Comment by cezannec** [comment]
This has now been fixed, and the code should update if you click Menu > Reset data. Thank you!
