### ISSUE TITLE
Implement route planner: missing rubric?

### ISSUE THREAD

**Issue by ddrm86** [udacity/isdc_issues_tracker#188]
I cannot find a link to the project rubric in any of the five sections. Maybe it is in the last one? 

I cannot check this because I already passed the project, since I was a reviewer for this one long before I was a beta-tester, and I think the content of this page changes.

**Comment by JonathanKSullivan** [comment]
@dsilver829 I can't seem to find any projects that have rubrics linked in the classroom. Is this something that we need to add to all projects, this one, or none?

**Comment by JonathanKSullivan** [comment]
Add rubric for all projects
