### ISSUE TITLE
Challenge: Shortest Path "Don't print" message

### ISSUE THREAD

**Issue by mvirgo** [udacity/isdc_issues_tracker#194]
The Challenge: Shortest Path quiz gives an error "Please don't print anything from your code!" even with the correct answer in the quiz.

**Comment by JonathanKSullivan** [comment]
Is this the quiz you are talking about. 

https://classroom.udacity.com/nanodegrees/nd113/parts/ad7e52df-3387-4252-b4bd-9c40aecb8093/modules/14fc0233-3169-4ca5-8255-ed921d2d973a/lessons/56980e75-08e4-4b3c-ba7f-58f10e963980/concepts/6146c6bc-68c8-498b-b6bd-8c16bee2886b

If so don't see the error.

**Comment by javoweb** [comment]
I have the same issue  in isdc-orientation Lesson 2.12 The Challenge: Shortest Path
