### ISSUE TITLE
Mistake in Carla Chronicles infographic

### ISSUE THREAD

**Issue by subamrana** [udacity/isdc_issues_tracker#2]
On this page (https://classroom.udacity.com/nanodegrees/nd113/parts/ad7e52df-3387-4252-b4bd-9c40aecb8093/modules/14fc0233-3169-4ca5-8255-ed921d2d973a/lessons/56980e75-08e4-4b3c-ba7f-58f10e963980/concepts/6146c6bc-68c8-498b-b6bd-8c16bee2886b), there is an infographic showing four routes (L1, L2, L3, L4).

What the error is: L3 and L4 are on left side of car and L1 and L2 are on right side. Rest of page suggests that the left route is L1 + L2 and right one is L3 + L4. So, that's the error.

Not too confusing but still an error.

**Comment by AndyAtUdacity** [comment]
Thanks for finding this! I just fixed the text to be consistent with the image.
