### ISSUE TITLE
Carla Chronicles programming quiz has ambiguous output

### ISSUE THREAD

**Issue by jchernus** [udacity/isdc_issues_tracker#200]
https://classroom.udacity.com/nanodegrees/nd113/parts/ad7e52df-3387-4252-b4bd-9c40aecb8093/modules/14fc0233-3169-4ca5-8255-ed921d2d973a/lessons/56980e75-08e4-4b3c-ba7f-58f10e963980/concepts/6146c6bc-68c8-498b-b6bd-8c16bee2886b

Test run output suggests solution is correct.

Submitting suggests there is an error. Tells me not to output anything (my code doesn't print anything).

**Comment by JonathanKSullivan** [comment]
Same as issue #194.
