### ISSUE TITLE
Parallel Parking - Submit button

### ISSUE THREAD

**Issue by wgcv** [udacity/isdc_issues_tracker#212]
In Joy Ride - Part 3: Parallel Parking there says that exist a submit button but you need to download manually and upload to the revision. Need to update the steps to download or add the submit button to the notebook.

**Comment by wgcv** [comment]
![Screen Shot 2018-03-14 at 2.31.46 AM.png](https://waffleio-direct-uploads-production.s3.amazonaws.com/uploads/5aa8d5c384038000110f7d9a/125516c66e82c728ace21e0d46db978826878de9bce1b057e40fa0c5710b77206455f76b7191a37af1112a4f5b595edd3c4a4356bcbbd671f3e57862804e0ee483645a70c26f11afb1d61bb801ba21d949d3e2b88e1ad2f42f67b6d5db1063474f4dcbed5727a29b41c95df44ae14c51a716326ae37f2431.png)

**Comment by wgcv** [comment]
https://classroom.udacity.com/nanodegrees/nd113/parts/70e3b7ce-c552-4867-984e-ebbfb6c786ec/modules/bb316d89-3a59-4093-b62d-f36d7822e530/lessons/8d04c12d-4214-443f-a933-d37f2544e718/concepts/3b467d7f-2e87-4a49-b001-e5a69c75414b

**Comment by wgcv** [comment]
The support of udacity solved the problem.

**Comment by JonathanKSullivan** [comment]
Thanks
