### ISSUE TITLE
can not reproduce the bug in histogram filter python version

### ISSUE THREAD

**Issue by hanxiaomax** [udacity/isdc_issues_tracker#213]

**Comment by JonathanKSullivan** [comment]
Is this still an issue?

**Comment by hanxiaomax** [comment]
i did not test it recently , i will do the test today. can you tell me what is the right way to reproduce that bug in case i am not doing it right.

as i know ,many students have this problem (we sign this class from udacity china )

**Comment by hanxiaomax** [comment]
in Notebook - Two Dimensional Histogram Filter , students are asked to reproduce a bug:

> ## Part 3: Identify and Reproduce a Bug
> Software has bugs. That's okay.
> 
> A user of your robot called tech support with a complaint
> 
> > "So I was using your robot in a square room and everything was fine. Then I tried loading in a map for a rectangular room and it drove around for a couple seconds and then suddenly stopped working. Fix it!"
> 
> Now we have to debug. We are going to use a systematic approach.
> 
> 1. Reproduce the bug
> 2. Read (and understand) the error message (when one exists)
> 3. Write a test that triggers the bug.
> 4. Generate a hypothesis for the cause of the bug.
> 5. Try a solution. If it fixes the bug, great! If not, go back to step 4.


in step 2:

> If you triggered the bug, you should see an error message directly above this cell. The end of that message should say:
> 
> IndexError: list index out of range
> And just above that you should see something like
> 
> path/to/your/directory/localizer.pyc in move(dy, dx, beliefs, blurring)
>      38             new_i = (i + dy ) % width
>      39             new_j = (j + dx ) % height
> ---> 40             new_G[int(new_i)][int(new_j)] = cell
>      41     return blur(new_G, blurring)
> This tells us that line 40 (in the move function) is causing an IndexError because "list index out of range".
> 
> If you aren't sure what this means, use Google!

but the bug never shows up ! i tried to run 
```
for i in range(10009):
    simulation.run(1)
simulation.show_beliefs()
```
and it's not working

**Comment by JonathanKSullivan** [comment]
Thank You Fixed!
