### ISSUE TITLE
P2 Python to C++ Pass Requirments

### ISSUE THREAD

**Issue by shad7867** [udacity/isdc_issues_tracker#218]

**Comment by shad7867** [comment]
The issue is that simulate.ccp which is included with the code sample download seems to suggest from the comments field that it needs completion "/**
simulate.cpp

Purpose: implements a Simulation class which
simulates a robot living in a 2D world. Relies
on localization code from localizer.py

This file is incomplete! Your job is to make
this code work.
*/"

However as clarified with Jonathan Sallivan, that is not the case, only need to run tests.cpp and make sure tests.cpp passes all results

**Comment by JonathanKSullivan** [comment]
Must uncomment the main method of simulate.cpp to run `simulate.cpp`
