### ISSUE TITLE
Greedy best-first search could be better defined

### ISSUE THREAD

**Issue by christophomos** [udacity/isdc_issues_tracker#219]

**Comment by christophomos** [comment]
In:
6. Navigating DataStructures ->
3. The Search Problem
23. On Uniform Cost

Greedy best-first search could be better defined. I think it would be best if the difference between A*, optimal and greed best-first searches are clearly compared and contrasted, which is quite simple. A* expands in terms of the function f:
f = g + h, where g is the path to the node so far and h is the estimate to the goal. Basically, optimal search ignores the h term and greed best-first ignores the g term.

**Comment by mvirgo** [comment]
Good idea! We've added a little more text here to further expand on this idea, as well as later in the lesson.
