### ISSUE TITLE
Issue with simulator on joy ride

### ISSUE THREAD

**Issue by araswan** [udacity/isdc_issues_tracker#22]

**Comment by araswan** [comment]
Problem In the joy ride project, the unity simulator is not always working properly, now it not responding to ctrl plus enter commands

Attempt I have tried to restart launching simulator, i have even opened the project again and restarted stuff.

**Comment by AndyAtUdacity** [comment]
This has been fixed by hosting large resources on Udacity's CDN instead of AWS
