### ISSUE TITLE
Traffic Light Classifier issue in red/green misclassification

### ISSUE THREAD

**Issue by mohamedkamalabdelwahed** [udacity/isdc_issues_tracker#222]
in test_functions.py line #57 in traffic light classifier project to check if there's any red light signs are misclassified as green signs

it's written as follows :
                   _self.assertNotEqual(*true_label*, [0, 0, 1])_
however it should be
                   _self.assertNotEqual(*predicted_label*, [0, 0, 1])_

**Comment by JonathanKSullivan** [comment]
Done! Thank you!
