### ISSUE TITLE
Quiz Language

### ISSUE THREAD

**Issue by BinuDavid** [udacity/isdc_issues_tracker#227]
Languages vary from one quiz to another

**Comment by BinuDavid** [comment]
In intro to python programming > Lesson 3: Control Flow > #11. Quiz with title: Modify Usernames with Range shows #commented lines that are in a different language. When submitting the quiz, the response is in the same language. The language displayed for comments and submissions for the other quizzes are in english.

**Comment by mvirgo** [comment]
Looks like this was for a different class than iSDC, although it's since been fixed. Thanks for noting!
