### ISSUE TITLE
Forum Languages

### ISSUE THREAD

**Issue by BinuDavid** [udacity/isdc_issues_tracker#228]
Languages in forums should be modified based on the reader's language setting

**Comment by BinuDavid** [comment]
I was reading the forums and noticed that some entries written in other languages had no one respond to them, possibly as a result of no one being able to read the language. If possible, please translate the languages based on the reader's language option. This should help to make sure that more student will have questions handled.

**Comment by JonathanKSullivan** [comment]
Doesn't seem that Discourse has built-in functionality for this, however, there is a 3rd-party provider that can localize discourse content.
https://www.transifex.com/discourse/discourse-org/

**Comment by mvirgo** [comment]
As the forums were deprecated in favor of [Knowledge](knowledge.udacity.com), closing this out.
