### ISSUE TITLE
student progress indicator flaw

### ISSUE THREAD

**Issue by tarunbelagodu** [udacity/isdc_issues_tracker#229]
In the Intro to Self Driving ND, the web interface indicates "You have completed all Part 2 requirements" - however there are 4 lessons that are at varying completion %. I am a student and this report is based on my Udacity profile. This status reporting display bar is incorrect and therefore misleading

**Comment by mvirgo** [comment]
Hi there! The only "requirements" in the classroom are the projects - therefore, once you've completed the projects, the classroom will show you this message. Viewing each and every page within a given lesson is not required. I'll forward on your feedback to the classroom team on why this could be misleading.

**Comment by tarunbelagodu** [comment]
Ah ok, I see what you mean. Then perhaps it should just be a project status. For example, in my case, I am currently in module "Implement route planner". Progress indicates 81%. When I dig deeper, lesson 1 is at 55%, lessons 2 & 3 are done (viewed), and the project is yet to be done. If the top level 81% indicator was only for the project, then it should have been 0% since my project has not begun. Does that explain the problem a little better from a student user perspective?
