### ISSUE TITLE
Probability of Collision [Exercise] "Try Again" After Correct Result

### ISSUE THREAD

**Issue by zeeexsixare** [udacity/isdc_issues_tracker#23]
On Lesson 5: Programming Probability in Python, I tested my code, got 4 out of 4 correct, and after submitting the answer it says "Try Again" and "Thank you for your submission."  Even if it doesn't check for success, it shouldn't recommend to try again if I passed.

**Comment by AndyAtUdacity** [comment]
Fixed!
