### ISSUE TITLE
joy ride 3

### ISSUE THREAD

**Issue by colowl** [udacity/isdc_issues_tracker#231]
i cant seem to get the car to do anything. There is also an error that pops out at the bottom of the code

**Comment by colowl** [comment]
![joyride3.png](https://waffleio-direct-uploads-production.s3.amazonaws.com/uploads/5b34025f1328d00011ba60a3/125516c66e82c728ace21e0d46e29b83318b87acdcabf301b44fff9e2c4533317346f67272dcb67ceb402b52560b4aab41585e16faafdd2fa2e02e6c981e5ab38532022d8c6853beb2901eb80bbb25884f87b5bb8f49c9e93820f5c6.png)

**Comment by JonathanKSullivan** [comment]
Student has bug in code
