### ISSUE TITLE
Lesson 11: 24.quiz move twice

### ISSUE THREAD

**Issue by stevenandersonz** [udacity/isdc_issues_tracker#232]
When a student introduces a wrong answer to the quiz it responds with the feedback of "Thanks for your submission" instead of "Incorrect submission" or something like that.

**Comment by stevenandersonz** [comment]
This is the link to the quiz: 
Bayesian Thinking, lesson 11, lecture 24
* https://classroom.udacity.com/nanodegrees/nd113/parts/70e3b7ce-c552-4867-984e-ebbfb6c786ec/modules/bb316d89-3a59-4093-b62d-f36d7822e530/lessons/7b8dd720-f17d-4ac5-856f-d152481be273/concepts/487491490923

**Comment by mvirgo** [comment]
Nice catch! We have updated the backend for this, so it should work appropriately now (quiz may need to be reset first).
