### ISSUE TITLE
Joy Ride 3 - Instruction Clarification

### ISSUE THREAD

**Issue by TimR31** [udacity/isdc_issues_tracker#234]

**Comment by TimR31** [comment]
Can I suggest in Parallel Parking, this line of code comment is changed: "# After running any code changes make sure to click the button "Restart Connection" above first.

# Also make sure to click Reset in the simulator to refresh the connection."

It seems to suggest the correct order is 1. Evaluate Cell 2. Press "Restart Connection" 3. Reset button in sim

However this will result in the car not moving.

It should be 2. 1. 3.

How about

"# After making any code changes, make sure to click the button "Restart Connection" above first. Then re-run your code cell (Ctrl+Enter).

# Also make sure to click Reset in the simulator to refresh the connection."

Phillip Robb added the following suggestion:
"It needs to also reference that you need to wait for the Kernel Ready message. I agree that this needs to be addressed as it was really frustrating."

**Comment by JonathanKSullivan** [comment]
Thanks for feedback
