### ISSUE TITLE
Reflections on project 2 - Translate Python to C++

### ISSUE THREAD

**Issue by vicsperry** [udacity/isdc_issues_tracker#235]
The starter code and the provided test cases could be better.

Whoever wrote the starter code has given new C++ programmers an example of how to quickly get something working by having .cpp files include other .cpp files. My experience suggests that some of the students will carry this forward into their jobs, if it helps them compete with their peers by coding faster. But, of course, that is the wrong way to code. I think the starter code should have been properly decomposed into appropriate .cpp and .h files. I wrestled with whether or not I should do this myself, but I realized I'd just be making everything harder for the reviewer, so I left the structure alone. It was difficult for me to allow myself to do that!

The test cases were mostly adequate, but in prototyping my "blur" function, I learned details about how C++ modulo works that I suspect would have tripped up anybody who blindly translated the Python code into C++. One additional test case with "move" moving from position 0,0 with dx,dy =-1,-1 would have been very instructive. It made me wonder what other subtle bugs may be lurking in my code. I wish there had been more comprehensive test cases provided.

**Comment by mvirgo** [comment]
Definitely valid feedback.

Have now added some additional tips to the classroom to help guide students at the start, as well as some hints around how modulo works in C++ vs. Python. Also fixed a bug around the `sense` function that cropped up on certain compilers (or moreso that some compilers were allowing the bug to persist).

Have added an internal ticket around updating the code to use proper C++ techniques, especially header files, so I'll update here when that is done.

**Comment by mvirgo** [comment]
Finished the code refactor here, so closing out.
