### ISSUE TITLE
ISDC - Lesson 6-15 - subtitles incorrect language

### ISSUE THREAD

**Issue by TimR31** [udacity/isdc_issues_tracker#236]
The subtitles on this YouTube video in Bayes' Rule say they're UK English, but it looks like Thai? I'm guessing they've got mislabeled, although it doesn't look like Thai is a language option...

**Comment by TimR31** [comment]
![thai.JPG](https://waffleio-direct-uploads-production.s3.amazonaws.com/uploads/5b3af6301ff11000147eebe8/125516c66e82c728ace21e0d46fc9c9b2ac0cfeb9ffbb049a15ee4d67304722a2b5df67f2487b37be6462f565f5f4ffe470e0b40f8af9b37b4f46d2ede0356b49b381d66cc2f10a5b2831abc00bb228a4c8cb2be8c48d2a5.JPG)

**Comment by TimR31** [comment]
Appears to be affecting quite a few of the videos in Bayes' Rule, 15 through to 26

**Comment by TimR31** [comment]
And Robot Sensing 8

**Comment by mvirgo** [comment]
Looks like these are back to normal now - thanks for noting!
