### ISSUE TITLE
Implement matrix: missing test case

### ISSUE THREAD

**Issue by tarunbelagodu** [udacity/isdc_issues_tracker#237]
Although I had a typo in the 1x1 determinant case for calculating Inverse, the test passed. Test package is missing a test case for 1x1.
In test.py, I see this with seemingly incorrect comments
assert equal(m1_x_m2.inverse(), m1_m2_inv), """Error in your inverse function for the 1 x 1 case"""

m1xm2 is not a 1x1 matrix

**Comment by mvirgo** [comment]
Nice catch - have now appropriately added a 1x1 test case.
