### ISSUE TITLE
Material update: In Module C++ Basics, Lesson 3

### ISSUE THREAD

**Issue by tarunbelagodu** [udacity/isdc_issues_tracker#238]
In Module C++ Basics, Lesson 3:
1. The guide document for IDE setup suggests moving the .sln file to parent directory, along with the .vcproj file. To avoid errors, the .sln file needs to be hand modified with updated path.
2. Also, the link in "Running Code Locally" is non-existant Visual C++ Build Tools

**Comment by mvirgo** [comment]
Thanks for noting these!

1. Added a note regarding this to the classroom.
2. Replaced the link with a working one
