### ISSUE TITLE
Error in ud711 Lesson 4

### ISSUE THREAD

**Issue by tinkledoomhammer** [udacity/isdc_issues_tracker#241]
In ud711, Object oriented javascript (not to be confused with ud015 which has the same name) in Lesson 4, section 3 "Functional Mixins" the quiz has an incorrect answer. 

The fourth option, "A factory function is normally called with the `new` operator" seems to be missing a "not."

**Comment by mvirgo** [comment]
This is only for Intro to Self-Driving Cars; closing.
