### ISSUE TITLE
Sigma Point Prediction Assignment 1

### ISSUE THREAD

**Issue by jacobnzw** [udacity/isdc_issues_tracker#242]
Sigma Point Prediction Assignment 1 in SDC ND won't compile correctly.
I get the following message:

In file included from Core:254:0,
                 from Dense:1,
                 from ukf.h:3,
                 from ukf.cpp:2:
DenseCoeffsBase.h: In instantiation of ‘Eigen::DenseCoeffsBase<Derived, 1>::Scalar& Eigen::DenseCoeffsBase<Derived, 1>::operator[](Eigen::DenseCoeffsBase<Derived, 1>::Index) [with Derived = Eigen::Matrix<double, -1, -1>; Eigen::DenseCoeffsBase<Derived, 1>::Scalar = double; Eigen::DenseCoeffsBase<Derived, 1>::Index = long int]’:
ukf.cpp:51:30:   required from here
StaticAssert.h:114:9: error: ‘THE_BRACKET_OPERATOR_IS_ONLY_FOR_VECTORS__USE_THE_PARENTHESIS_OPERATOR_INSTEAD’ is not a member of ‘Eigen::internal::static_assertion<false>’
         if (Eigen::internal::static_assertion<bool(CONDITION)>::MSG) {}
         ^
DenseCoeffsBase.h:375:7: note: in expansion of macro ‘EIGEN_STATIC_ASSERT’
       EIGEN_STATIC_ASSERT(Derived::IsVectorAtCompileTime,
       ^
g++: error: ukf.o: No such file or directory

**Comment by jacobnzw** [comment]
My bad

**Comment by mvirgo** [comment]
Closing since for SDC, not iSDC
