### ISSUE TITLE
Python Histogram Filter - Part 3

### ISSUE THREAD

**Issue by TimR31** [udacity/isdc_issues_tracker#243]
The "bug" in Part 3 is already fixed in the localizer.py file provided. You can see the intended error in the Jupyter Notebook, but the solution is already implemented.

https://discussions.udacity.com/t/i-cannot-reproduce-theindexerror-bug/594729

https://carnd.slack.com/archives/C8HCH8A1L/p1521437994000137

**Comment by mvirgo** [comment]
Fixed this finally :) (requires a reset of your workspace)
