### ISSUE TITLE
Data Structures & Algorithms in Python - Lesson 2 - 7 Quiz

### ISSUE THREAD

**Issue by soham23** [udacity/isdc_issues_tracker#250]
Traceback (most recent call last):
  File "vm_main.py", line 33, in <module>
    import main
  File "*aPath*/main.py", line 2, in <module>
    import studentMain
  File "*aPath*/studentMain.py", line 1
SyntaxError: Non-ASCII character '\xc3' in file *aPath*/studentMain.py on line 1, but no encoding declared; see http://www.python.org/peps/pep-0263.html for details

**Comment by mvirgo** [comment]
Looks like something on the backend was in Spanish and had a non-ASCII character in it - looks like a translation mistake. Fixed!
