### ISSUE TITLE
Implement Route Planner: buggy line causing interpreter error

### ISSUE THREAD

**Issue by ddrm86** [udacity/isdc_issues_tracker#255]
The starting code has a buggy line that is confusing students, that are usually new to programming since this is an intro course. This is an actual complaint in the notebook submitted by a student: 

    #PathPlanner._reset = _reset  #Lost a whole night dealing with this, not being able to proceed with the trials. 
    # Not very nice to the student!!!!

That line should not exist or be commented out, since the _reset method is already implemented inside the PathPlanner class, and there is no _reset object in the outer scope, so the assignment throws an error.

**Comment by mvirgo** [comment]
Removed the line - thanks for noting.
