### ISSUE TITLE
Lesson 4 - 22 C++ Basics

### ISSUE THREAD

**Issue by DeniseJames** [udacity/isdc_issues_tracker#26]
The C++ program to be translated from Python is challenging.  I took a day to create the solution.  https://github.com/DeniseJames/iSDC  As a student I would like to see the solution in the lectures.

**Comment by andrewpaster** [comment]
Hey Denise, thanks for the feedback. And sorry it's taken so long for us to respond. Is this in reference to the Python to C++ translation project? Since this project gets submitted and reviewed, I'm guessing the team won't want to post a solution in the classroom. But I'll bring this up.

**Comment by DeniseJames** [comment]
Andrew,

When I submitted this, I do not believe it was a project.  Please close it
down.

**Comment by andrewsdc** [comment]
Ok thanks!
