### ISSUE TITLE
Android Nano Degree Quizz Show map

### ISSUE THREAD

**Issue by hbauza14** [udacity/isdc_issues_tracker#260]

**Comment by hbauza14** [comment]
Here this example doesn't work in Android Oreo,I put the street and the intent just opened the map and don't show me the street
![Screenshot from 2018-10-03 21-09-22.png](https://waffleio-direct-uploads-production.s3.amazonaws.com/uploads/5bb567c61575e900137abbf0/125516c66e82c728ace21e0d46db978826878dba87e6ab03a24fff99691477227149f27b3dd5b068ed13365156424cae53444d04bea6d37ef5f22e7a985902bfd8685b70943d12a5ec8618bf01bb728d19d1b2b8dc5edcfa7f74b9dfd0126754505a9bf54f34a8934acd5bfe4de04856a3153265ef647b.png)

**Comment by mvirgo** [comment]
This is not the Waffle board for Android ND.
