### ISSUE TITLE
Notebook: Accuracy and Misclassification already filled out

### ISSUE THREAD

**Issue by cswksu** [udacity/isdc_issues_tracker#263]
The "To Do" sections of the notebook are already filled in on loading the notebook. After resetting the data of the Juniper Notebook, they are still present.

**Comment by cswksu** [comment]
The "To Do" sections of the notebook are already filled in on loading the notebook. After resetting the data of the Juniper Notebook, they are still present.

**Comment by mvirgo** [comment]
Thanks @cswksu - which notebook is this?

**Comment by cswksu** [comment]
It's included in the Computer Vision section of the course.

**Comment by mvirgo** [comment]
Thanks again for noting this! Have now removed some of the "solved" code from the TO-DO's and cleared the output of this notebook (note that `reset data` must be used in the workspace for it to pull in the updated, cleared notebook).
