### ISSUE TITLE
Out of order content

### ISSUE THREAD

**Issue by josahe** [udacity/isdc_issues_tracker#265]
In 'Lesson 6: Introduction to Neural Networks' there is one video that seems to be in the wrong place. It is currently '18 Non-Linear Regions'. But I think it should come down after '33 Continuous Perceptrons'. It is very confusing where it currently is.

**Comment by mvirgo** [comment]
I think it actually makes the most sense just to drop this video - it seems like it covers most of the same material as the two other videos about "Non-Linear X". Good catch!
