### ISSUE TITLE
TYPO

### ISSUE THREAD

**Issue by karanjoshi260** [udacity/isdc_issues_tracker#266]
URL - https://classroom.udacity.com/courses/ud283/lessons/008b74dd-d786-4d22-84e6-ace8ae102ba4/concepts/b4edf2ab-30f8-481e-ae42-d0570d03f641

Content - 2nd last word of the sentence has the mistake.
Methods in Java are functions that belong to a particular object. When we get to creating our own object types later in this lesson we will be creating methods the same way we used to created functions.

**Comment by mvirgo** [comment]
This is the issue tracker for Intro to Self-Driving Car. Please only open tickets related to this program.
