### ISSUE TITLE
Reference Link Issue

### ISSUE THREAD

**Issue by shawkyelshazly1** [udacity/isdc_issues_tracker#268]
On the first page of the 1MAC android track course,there is a reference link to the discussion forms named " Introduce yourself ", However the link is corrupted as it starts with "hhttps" instead of "https", 
HYG the lnik : hhttps://macdiscussions.udacity.com/t/read-me-cohort-4-introduction/263953

**Comment by mvirgo** [comment]
This is the Waffle board for Intro to Self-Driving Cars; please do not open tickets for other courses here.
