### ISSUE TITLE
Small error in Deep Learning Video

### ISSUE THREAD

**Issue by soswow** [udacity/isdc_issues_tracker#272]
Deep Learning Nanodegree Program -> Neural Networks -> Introduction to NN -> Multi-class Entropy -> Video -> 2:38

He says "m is a number of classes"
But whole visual is contradicting to itself.
In the table p11, p12, p13 are all probabilities for first class (Duck) so, first number after "p" must be index of a class. But in the formula first index is "i" which goes from 1 to n. So n should be number of classes.

**Comment by mvirgo** [comment]
This is only the board for Intro to Self-Driving Car, please do not open unrelated tickets here.

**Comment by soswow** [comment]
Sorry about that. Would you mind pointing me at the right board instead?

**Comment by mvirgo** [comment]
I believe [this](https://waffle.io/udacity/dlnd-issue-reports) is it.
