### ISSUE TITLE
autoregression_quiz notebook

### ISSUE THREAD

**Issue by mcreatura** [udacity/isdc_issues_tracker#273]
Within the Nanodegree "AI for Trading" / Lesson 13 Time Series Modeling / Exercise: ARMA and ARIMA / autoregression_quiz the link "Check out the stats model arima documentation to help you." is wrong, it shows the documentation for the ARMA. The link https://www.statsmodels.org/dev/generated/statsmodels.tsa.arima_model.ARIMA.html is the correct one.

**Comment by mvirgo** [comment]
This is only the Waffle board for Intro to Self Driving Car. Please only leave issues for this Nanodegree here.
