### ISSUE TITLE
Workspace error

### ISSUE THREAD

**Issue by megbeshai** [udacity/isdc_issues_tracker#274]
Workspace not loading correctly despite reloading workspace. I can at least pick from the student files after I reload but I am not sure which file goes with the lesson I am on. 
I have screen grabs of the errors from chrome inspector

**Comment by megbeshai** [comment]
<img width="1440" alt="screen shot 2018-11-25 at 4 58 27 pm" src="https://user-images.githubusercontent.com/44876738/48987523-a5313a80-f0d4-11e8-9487-cd2a2e3ab69b.png">
<img width="1440" alt="screen shot 2018-11-25 at 5 00 07 pm" src="https://user-images.githubusercontent.com/44876738/48987524-a5313a80-f0d4-11e8-9635-b52a7b54d4e2.png">
<img width="1440" alt="screen shot 2018-11-25 at 5 00 03 pm" src="https://user-images.githubusercontent.com/44876738/48987525-a5c9d100-f0d4-11e8-9a5a-0b4d82f065c6.png">

**Comment by mvirgo** [comment]
This is only the Waffle board for Intro to Self-Driving Car, please do not leave unrelated issues here.

**Comment by megbeshai** [comment]
In the future, a more student first response would be appreciated. I obviously did not intend to post in the wrong waffle board and was linked to this board from an FAQ. The goal of reporting the bug was a) so that I could continue to work on my nanodegree and b) so Udacity would not look bad because it had outstanding bugs. In the future, I would recommend a more polite response and forwarding the bug to the correct person or pointing me to the correct waffle board. 
Thank you!
