### ISSUE TITLE
On Lesson 9: Programming Probability Distributions, section 4. Uniform Distribution [exercise]

### ISSUE THREAD

**Issue by zeeexsixare** [udacity/isdc_issues_tracker#28]
Typo on maximum value shown below.  It says 0 and should be 360:

Uniform Probability Distribution Function¶
The probability_uniform function calculates the probability of an event given a range of values from a uniform continuous probability distribution.
low_range is the low end of the region of interest
high_range is the high end of the region of interest
minimum is the minimum value of the uniform probability distribution (0 for a spinning wheel)
maximum is the maximum value of the uniform probability distribution --->(0 <-----for a spinning wheel).*

**Comment by AndyAtUdacity** [comment]
fixed!
