### ISSUE TITLE
Typo in Challenge:Shortest Path in Lesson 2

### ISSUE THREAD

**Issue by cwoolum** [udacity/isdc_issues_tracker#3]
In the comments of the test_make_decision function, the comment says 
    
    # TEST 1, should return "R" since left path has 
    # length 5 which is < left path with length 8

It should say 

    # TEST 1, should return "R" since right path has 
    # length 5 which is < left path with length 8

![image](https://user-images.githubusercontent.com/942415/31252796-3b94548a-a9d7-11e7-80b3-c8d18e133e59.png)

**Comment by AndyAtUdacity** [comment]
Fixed!
