### ISSUE TITLE
bug in sample_means_calculator

### ISSUE THREAD

**Issue by alevchuk** [udacity/isdc_issues_tracker#37]
8_central_limit_theorem_demo has a bug

in
def sample_means_calculator(
...
ax5 = plt.subplot(121)
stats.probplot(probability_distribution, plot=plt)

probability_distribution should be "distribution"

because probability_distribution is a variable from outside scope that was declared in an earlier code, it's not related to this function

**Comment by alevchuk** [comment]
8_central_limit_theorem_demo

in
  def sample_means_calculator(
    ...
    ax5 = plt.subplot(121)
    stats.probplot(probability_distribution, plot=plt)


probability_distribution should be "distribution"

because probability_distribution is a variable from outside scope that was declared in an earlier code, it's not related to this function

**Comment by AndyAtUdacity** [comment]
Great catch thank you! Just fixed this.
