### ISSUE TITLE
Can't access discussion forum

### ISSUE THREAD

**Issue by heretoinfinity** [udacity/isdc_issues_tracker#4]

**Comment by heretoinfinity** [comment]
When I click on the link below, I am told "Oops! That page doesn’t exist or is private."
https://discussions.udacity.com/c/nd113-welcome-to-isdc

**Comment by minrafa** [comment]
experiencing same problem

**Comment by erikaalonzo** [comment]
Hi! What is your forum user name so I can authorize access?

**Comment by heretoinfinity** [comment]
@erikaalonzo Were you referring to me? Where did you want me to post it here for everyone?

**Comment by erikaalonzo** [comment]
You can email into introsdc-support@udacity.com if you prefer to keep your username private.

**Comment by andrewsdc** [comment]
Hi, I'm assuming this has been resolved. So I'm going to close the issue. If you're still having trouble accessing the forum, please write to  introsdc-support@udacity.com
