### ISSUE TITLE
Typo in Notebook: Two Dimensional Histogram Filter

### ISSUE THREAD

**Issue by carsten-grimm** [udacity/isdc_issues_tracker#41]

**Comment by carsten-grimm** [comment]
The second code cell reads: 

# This code defines a 4x4 robot world as well as some other parameters
# which we will discuss later. It then creates a simulation and shows 
# the initial beliefs. 
R = 'r'
G = 'g'
grid = [
    [R,G,G,G,R],
    [G,G,R,G,R],
    [G,R,G,G,G],
    [R,R,G,R,G],
    [R,G,R,G,R],
]

This looks like a 5x5 robot world to me ;-)

**Comment by carsten-grimm** [comment]
The second code cell reads:
```
# This code defines a 4x4 robot world as well as some other parameters
# which we will discuss later. It then creates a simulation and shows 
# the initial beliefs. 
R = 'r'
G = 'g'
grid = [
    [R,G,G,G,R],
    [G,G,R,G,R],
    [G,R,G,G,G],
    [R,R,G,R,G],
    [R,G,R,G,R],
]
```
This looks like a 5x5 robot world to me ;-)

**Comment by carsten-grimm** [comment]
Sorry, I did not realize that Waffle uses Markdown automatically.

**Comment by AndyAtUdacity** [comment]
thanks, fixed!
