### ISSUE TITLE
L4: Cond. Prob. - Node: Learning Objectives - Conditional Probability

### ISSUE THREAD

**Issue by JonathanKSullivan** [udacity/isdc_issues_tracker#42]
In L4: Cond. Prob. , in the Node titled, Learning Objectives - Conditional Probability, Question 3 of 5 Implies that the student know Bayes rules. Im not sure If this is intentional but seems like it should be moved to the Bayes rule section.

**Comment by xperroni** [comment]
This is intentional, as explained in Lesson 4.5:

_After reviewing the previous lesson's learning objectives_ [in Lesson 4.6], _you'll preview this lesson's learning objectives_ [in Lesson 4.7]. _Remember: you aren't expected to know the answers to these yet._
