### ISSUE TITLE
Latex rendering error on iOS on L3: Prob. - Node Two Cars 1-5

### ISSUE THREAD

**Issue by JonathanKSullivan** [udacity/isdc_issues_tracker#43]
The fractions for Q1 show up fine on web but on iphone render as 
P(L) = \frac{1}{3}
P(S) = \frac{1}{3}
P(R) = \frac{1}{3}

**Comment by AndyAtUdacity** [comment]
Oh this is troubling. Likely means that LaTeX rendering isn't supported on iOS.
