### ISSUE TITLE
C++ Basics - L1 - While and For Loops

### ISSUE THREAD

**Issue by AndyAtUdacity** [udacity/isdc_issues_tracker#48]

**Comment by AndyAtUdacity** [comment]
From Percy in Slack

> it says that when 'for' loop is executed, it first initializes 'int I', check for condition i < elapsed_time.
"If true, then i increases by one and the code in the for loop will run."
Shouldnt it be other way around, once the condition "i < elapsed_time" is checked, loop should get executed first and then value of i should be incremented. Because if value is incremented first and then loop is executed, I would never get loop iteration with first value of i=0.

**Comment by andrewsdc** [comment]
Clarified the language. Classroom made it sound like incrementation and code happened simultaneously.
