### ISSUE TITLE
C++ Basics - L3 - Class Variables

### ISSUE THREAD

**Issue by AndyAtUdacity** [udacity/isdc_issues_tracker#49]
in playground line# 11 and 12, it says to define "an integer size_type variable called rows" I think it should be reworded to say  define a size_type for a vector holding float values.
I would define "an integer size_type variable called rows" as => int::size_type rows; which is not what we need.

**Comment by AndyAtUdacity** [comment]
Comes from Percy in slack

**Comment by andrewpaster** [comment]
changed to: 
a vector size_type variable called rows
a vector size_type variable called cols

Hopefully that clarifies.
