### ISSUE TITLE
Can`t access C++ link learning resource

### ISSUE THREAD

**Issue by warlockz** [udacity/isdc_issues_tracker#5]
https://www.udacity.com/course/c-for-programmers--ud210

**Comment by warlockz** [comment]
Error :
404
Sorry, we can't seem to find 
the page you are looking for.

UDACITY HOME

**Comment by minrafa** [comment]
I have this problem too. Wrote to support team but haven't got any response yet.

**Comment by silentwater** [comment]
Duplicate of Defect #1

**Comment by AndyAtUdacity** [comment]
Thanks for pointing this out. I'm closing this issue since it's a duplicate of #1
