### ISSUE TITLE
C++ Basics - L3 - Class Variables (issue 2)

### ISSUE THREAD

**Issue by AndyAtUdacity** [udacity/isdc_issues_tracker#50]
Secondly, in solution you are defining aforementioned row as "std::vector<int>::size_type rows;"
should it be float instead of int inside vector parentheses?
I assume that this int or float wont matter as rows is supposed to keep count of number of elements, irrespective of whether its a int or float...but still firstly from concept point of view and secondly with C++'s all the background memory management perspective, will float / int make a difference while defining size_type for vector?

**Comment by AndyAtUdacity** [comment]
Also from Percy

**Comment by andrewsdc** [comment]
Reached out to the student on slack about this and made some changes in classroom.
