### ISSUE TITLE
General demand for a "course outline" w/ due dates

### ISSUE THREAD

**Issue by AndyAtUdacity** [udacity/isdc_issues_tracker#53]

**Comment by AndyAtUdacity** [comment]
![Screen Shot 2017-10-24 at 10.48.51 AM.png](https://waffleio-direct-uploads-production.s3.amazonaws.com/uploads/59d3ce5e2799da0012d136d3/125516c66e82c728ace21e0d46db978826878de9bce1b057e40fa0c57e0b76236456f76b7191a379ef0c2f59415a4fbc30254d58eeb9cb74fce36f34985619e8d83f5671c23943acbb8b4bbb06ba208a1d83e0e88e4896fa2137a5dad11b61435c52dcbd4f3fb2984cc259f34be94553a3103265e074306e0a.png)

**Comment by JonathanKSullivan** [comment]
Same as issue #196
