### ISSUE TITLE
L9 P10L Visualizing Uniform Distributions Solution

### ISSUE THREAD

**Issue by alexandervlahakis** [udacity/isdc_issues_tracker#57]
def plot_uniform(x_minimum, x_maximum, tick_interval):
    # plot points on x-axis from 0 to 360 including the value 360
    x = range(x_minimum, x_maximum + 1)
    y = 1/(x_maximum - x_minimum)

    plt.bar(x_minimum, y, bottom=0, width= (x_maximum - x_minimum), align='edge', alpha=0.5)
    plt.xlabel('Degrees')
    plt.ylabel('Probability Distribution')
    plt.title('Uniform Probability Distribution')
    plt.xticks(np.arange(min(x), max(x)+1, tick_interval))
    plt.ylim(0, .005)

    plt.show()

the `plt.ylim(0, .005)` sets a hard limit on the charts height, which will cut off the graph if the heigh is > .005.  Maybe implement as `plt.ylim(0, 1.5*y)` a dynamically sizing graph?

**Comment by andrewpaster** [comment]
Yeah that's a good point. We ended up reworking these exercises a bitt, so it's not an issue anymore. Thank you for bringing this up!
