### ISSUE TITLE
Missing Content in Part 3 "C++ Basics" Lesson 1 Part 2 "Lesson Overview"

### ISSUE THREAD

**Issue by carsten-grimm** [udacity/isdc_issues_tracker#59]
There is a list of instructions on how to get C++ running on your computer, but the list has only one item regarding the editor / the ide.

**Comment by andrewsdc** [comment]
Hi, thanks for pointing this out. I reformatted the text so hopefully it makes more sense. You can run C++ within the classroom. Or we suggest downloading one of the IDEs mentioned: either Xcode for Mac or Visual Studio, which is available for either Mac or Windows.
