### ISSUE TITLE
Typo in Lesson 3.20

### ISSUE THREAD

**Issue by KestasJ** [udacity/isdc_issues_tracker#61]
" is is" :

The above version, adds together the state variables! Or.. you may choose to just print out that adding cars is is an invalid operation, as below.

**Comment by KestasJ** [comment]
![Capturea.PNG](https://waffleio-direct-uploads-production.s3.amazonaws.com/uploads/59f7adfd095e120011d0a09d/125516c66e82c728ace21e0d46cb958a379791ac8eabf301b44fff9e2c4533317346f67272dcb67ceb402b52560b4aab41585e16faafdd2fa2e02e6c981e5ab38532022d8c6853beb2901eb60bbb258b4681b6b8894ac8ef3f20f5c6.PNG)

**Comment by andrewpaster** [comment]
Thank you for finding this and letting us know. It's been fixed!
