### ISSUE TITLE
Lesson 9.16 2-D Car World classes

### ISSUE THREAD

**Issue by alexandervlahakis** [udacity/isdc_issues_tracker#62]
class Car():
    def __init__(self, color):
       self.color = 'red'

    def repaint(self, new_color):
      self.color = new_color

Given an example of instantiating new car objects..
carA = Car('red')
carB = Car('orange')
carC = Car('green')

The way the class itself is written cars will always be 'red', no matter the color argument input when instantiating the class.  

Below would give such functionality:
class Car():
    def __init__(self, color):
       self.color = color

**Comment by andrewsdc** [comment]
Thanks for catching this. I just updated the classroom.
