### ISSUE TITLE
Typo in Matrix Multiplication

### ISSUE THREAD

**Issue by zeeexsixare** [udacity/isdc_issues_tracker#63]
Lesson 3: State and Object Oriented Programming, 24. Matrix Multiplication says "text" your knowledge in the first sentence.  Should be "test."

**Comment by zeeexsixare** [comment]
![capture](https://user-images.githubusercontent.com/32753720/32204591-9b71fc20-bdc0-11e7-8b32-7e2a672b2310.PNG)

**Comment by andrewsdc** [comment]
Thanks for pointing this out and also providing the screen shot. Just fixed it!
