### ISSUE TITLE
In Matrices - Lesson 3 - Many blurry videos (possibly an exporting issue)

### ISSUE THREAD

**Issue by AndyAtUdacity** [udacity/isdc_issues_tracker#66]
For example: https://coco.udacity.com/nanodegrees/nd113/locale/en-us/versions/1.0.0/parts/389757/modules/346548/lessons/385145/concepts/410675 

I haven't looked through the whole lesson, but students have said that "most of the videos in the lesson are blurry". 

Possibly re-exporting at higher resolution would address some of these problems?

**Comment by zeeexsixare** [comment]
In this part of the lesson:

![image](https://user-images.githubusercontent.com/32753720/32356441-689f6da8-c00b-11e7-9a57-522beba1b59c.png)

The following youtube video plays, and it becomes pixellated/blurry about 0:20 into the video.
https://www.youtube.com/watch?time_continue=27&v=ASiIgcKYUy0
