### ISSUE TITLE
Typo in Vectors in Python

### ISSUE THREAD

**Issue by zeeexsixare** [udacity/isdc_issues_tracker#67]
There's a missing comma in the code shown in the attached screenshot.

**Comment by zeeexsixare** [comment]
![image](https://user-images.githubusercontent.com/32753720/32356199-deb7fdae-c009-11e7-814e-983a44eea7ad.png)

**Comment by andrewsdc** [comment]
Thanks for catching this and letting us know. I just fixed the typo :-).
