### ISSUE TITLE
Translate python to c++

### ISSUE THREAD

**Issue by sujaybabruwad** [udacity/isdc_issues_tracker#68]
compilation command is this g++ tests.cpp

But we need to specify the std library say g++ -std=c++11 tests.cpp

If not done we get this error 
helpers.cpp:170:27: error: no matching function for call to ‘std::basic_ifstream<char>::basic_ifstream(std::__cxx11::string&)’
  ifstream infile(file_name);

Tested on my system:
Ubuntu 16.04
GCC 5.4

Need to update the command for scenarios like these.

**Comment by andrewpaster** [comment]
Hey thank you for bringing this to our attention. We've added better instructions in the classroom about this.
