### ISSUE TITLE
Lesson 3.4 Q 3 of 5 Formatting Issue in Answer

### ISSUE THREAD

**Issue by carsten-grimm** [udacity/isdc_issues_tracker#7]
The message that you see when you hit "submit" with the correct answer for Question 3 of 5 in Lesson 3 Part 4 contains a formatting error. 

The message is supposed to contain the product of three numbers a*b*c, yet Markdown formatting is applied and "b" becomes italic and there are no stars representing multiplication. 

Suggestion: Use LaTeX / MathJax whenever typesetting math anywhere.

**Comment by carsten-grimm** [comment]
The same problem occurs in other messages that are displayed when explaining correct quiz answers. For instance in Lesson 3 Part 18 Question 1, the explanation is nonsensical due to formatting issues.

**Comment by carsten-grimm** [comment]
The same problem occurs in Lesson 6 Part 6 Question 2 of 5.

**Comment by AndyAtUdacity** [comment]
fixed all 3 of these issues. Likely that there's a few more lingering... Thanks though!
