### ISSUE TITLE
Typo in Matrix Multiplication

### ISSUE THREAD

**Issue by zeeexsixare** [udacity/isdc_issues_tracker#70]
Typo in matrix multiplication, see screenshot.

**Comment by zeeexsixare** [comment]
![image](https://user-images.githubusercontent.com/32753720/32400835-c93b4274-c0db-11e7-909f-0c86bd5c7dcb.png)

**Comment by andrewsdc** [comment]
Thanks for catching this and letting us know. I just fixed the typo.
