### ISSUE TITLE
L3.6 State and OOP; Kinematics.. simple typo

### ISSUE THREAD

**Issue by alexandervlahakis** [udacity/isdc_issues_tracker#75]
"Kinematics is the study of the motion of objects. Motion models are also referred to as kinematic equations, and thee equations give you all the information you need to be able to predict the motion of a car."

"..and **three** equations give you all the information.."

three vs. thee.  I don't know if changes like these are too basic for waffle?

**Comment by andrewpaster** [comment]
Hey thanks. Yes, waffle is a good place to let us know about typos! It looks like it should've read "and these equations give you...".
