### ISSUE TITLE
Add link to Mac setup instructions for C++

### ISSUE THREAD

**Issue by AndyAtUdacity** [udacity/isdc_issues_tracker#77]
student in slack named alyxion made a great doc https://docs.google.com/document/d/1FoIc9X0NcM-0y0dgXCzJcpu5lVXGFqS62mb1ABLDT1M/edit

Let's find a home for it!

**Comment by andrewpaster** [comment]
Looks like this was done already in the beginning of the C++ basics lecture, and I just copied the instructions in the practical section as well. So students will have two chances to get things running locally.
