### ISSUE TITLE
C++ basics - go through review document made by Alyxion and make changes as appropriate

### ISSUE THREAD

**Issue by AndyAtUdacity** [udacity/isdc_issues_tracker#79]
https://docs.google.com/document/d/1XqUn7bT4k9DbUqu_HVpSgDNxVtuX3ShUlq0fLGKVcJY/edit#

**Comment by AndyAtUdacity** [comment]
I addressed the issues at the end of the doc. Leaving this open as a reminder to go through the entire doc more thoroughly.

**Comment by andrewpaster** [comment]
I went through this as well and made changes. This doc is also good as a starting off point for teaching advanced C++. I'm going to close this issue.
