### ISSUE TITLE
Issue in simulate.cpp

### ISSUE THREAD

**Issue by JonathanKSullivan** [udacity/isdc_issues_tracker#80]
There is a message at the top of the file that tells student to modify the file. It should be removed.

https://classroom.udacity.com/nanodegrees/nd113/parts/8a7dde4d-a66a-4666-8ddb-783ed670263b/modules/c7c475c8-da86-4f23-93b1-639baaec3e4e/lessons/269ac8b0-5f8d-43a8-bb05-426c277496c0/concepts/5db92d72-4d35-40c0-995f-e14759515808

**Comment by andrewpaster** [comment]
Was this ever resolved? It looks like it wasn't but not sure. I don't want to modify or break something since I haven't gone through this project yet.

**Comment by AndyAtUdacity** [comment]
Whoops! Just removed the line that says 
	This file is incomplete! Your job is to make 
	this code work.
