### ISSUE TITLE
Typo in C++ 2d Matrix

### ISSUE THREAD

**Issue by zeeexsixare** [udacity/isdc_issues_tracker#81]
1. Copes should be copies.  
2. Missing "the" in circled area

**Comment by zeeexsixare** [comment]
![image](https://user-images.githubusercontent.com/32753720/32695624-fe48f6ba-c72e-11e7-8bde-b47f871b846b.png)

**Comment by zeeexsixare** [comment]
![image](https://user-images.githubusercontent.com/32753720/32695640-6f721af6-c72f-11e7-81b9-f8bcba8fcb98.png)

**Comment by andrewpaster** [comment]
Thanks for letting us know. It's been fixed.
