### ISSUE TITLE
Links broken in Joy Ride's project review

### ISSUE THREAD

**Issue by david89** [udacity/isdc_issues_tracker#82]
In the project review section of the Joy Ride project, there are a few links under More In-depth Knowledge. Some of them are broken:
* Development of automated parallel parking system in small mobile
* Automated Parallel Parking and Automated Parallel Parking Robotic Car point to the same YouTube video.

**Comment by AndyAtUdacity** [comment]
I think this refers to your particular project review. I don't think these links are shared broadly with all students.
