### ISSUE TITLE
Typo in Anatomy of a Class

### ISSUE THREAD

**Issue by zeeexsixare** [udacity/isdc_issues_tracker#85]
guassian.cpp

**Comment by zeeexsixare** [comment]
![image](https://user-images.githubusercontent.com/32753720/32813638-39a168c2-c979-11e7-9a17-1b4259eeca97.png)

**Comment by zeeexsixare** [comment]
sigma2

**Comment by zeeexsixare** [comment]
![image](https://user-images.githubusercontent.com/32753720/32819226-04ecbe34-c996-11e7-85bc-ead0c572b441.png)

**Comment by andrewpaster** [comment]
Thanks for pointing this out. The typos are fixed!
