### ISSUE TITLE
The video on instructions to resubmit the project doesn't work

### ISSUE THREAD

**Issue by mohitdia** [udacity/isdc_issues_tracker#86]
On the Joy Ride project review page there is a link of a video titled "best practices for revising and resubmitting your project." But when I click on it nothing happens. I'm unable to proceed  to re-submit the project.

**Comment by AndyAtUdacity** [comment]
I'm not sure what the "project review page" refers to. @dsilver829 assigning this to you.

**Comment by mhernandezdev** [comment]
Same issue experienced - see attached
![udacity_review_video_issue](https://user-images.githubusercontent.com/34208530/35385120-5593698c-0195-11e8-9a08-32c093171db8.png)

**Comment by mhernandezdev** [comment]
Same issue experienced 
![udacity_review_video_issue](https://user-images.githubusercontent.com/34208530/35385557-acb03d66-0196-11e8-8154-3a1b45fa1b68.png)

**Comment by mvirgo** [comment]
Closing as it appears the video works
