### ISSUE TITLE
C++ Getting started,  C++ - A Statically Typed Language

### ISSUE THREAD

**Issue by JonathanKSullivan** [udacity/isdc_issues_tracker#94]
The earlier videos said we cannot run C++ in the browser for this lesson, so this led me to believe that all code would have to be done locally. However, this quiz runs C++ code.

**Comment by andrewpaster** [comment]
can't find the video where it said that. There was a text node in the lesson overview that said, "The classroom has embedded spaces where you can write and execute your C++ code directly in your browser; however, you may find it helpful to write C++ code on your own computer for this lesson (and not in the browser)."
