### ISSUE TITLE
C++ Getting started, Two Functions Same Name

### ISSUE THREAD

**Issue by JonathanKSullivan** [udacity/isdc_issues_tracker#95]
Students have already seen arrays, matrices, and vectors,  is the top video isn't really needed?

**Comment by andrewpaster** [comment]
I think at this point students haven't seen C++ vectors yet. Maybe it'd be better to make a new concept with the typedef info and put it after the "Two Dimensional Vectors" concept. And the current concept would start  "In the video below Andy discovered something surprising while translating his histogram filter code" would

**Comment by AndyAtUdacity** [comment]
Yeah I think this video is useful for the narrative and the introduction to C++ vectors. Plus it's only 45 seconds so there isn't much harm done in including this. I'm going to mark as closed.
