### ISSUE TITLE
C++ Getting started

### ISSUE THREAD

**Issue by JonathanKSullivan** [udacity/isdc_issues_tracker#99]
It will be really good if Dr. Stroustrup videos from ud210 are added as a additional resources.

The whole course assume students already know Python language, but some students may be completely new to programming.

**Comment by andrewpaster** [comment]
There is a link to UD210 in the classroom. Maybe it was placed in the classroom after this comment was made? It's in Orientation->Get Ready. In terms of " but some students may be completely new to programming". Having at least some programming experience is listed as a prerequisite.
